### ISSUE TITLE
Environment details to repeat training/evaluation

### ISSUE THREAD

**Issue by imduygusarikaya** [zhujiagang/st-gcn-data-len#3]
I am trying to repeat the evaluation on kinetics skeleton, and I have been having errors which I believe might be related to version conflict. For example:

loss_value.append(loss.data[0])
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

I fix it then I get another one:

Traceback (most recent call last):
  File "main.py", line 426, in <module>
    processor.start()
  File "main.py", line 388, in start
    epoch=0, save_score=self.arg.save_score, loader_name=['test'])
  File "main.py", line 352, in eval
    ln, len(self.data_loader[ln]), np.mean(loss_value)))
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 2957, in mean
    out=out, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py", line 80, in _mean
    ret = ret.dtype.type(ret / rcount)
AttributeError: 'torch.dtype' object has no attribute 'type'

etc.

Can you please write the environment you have run these code under? e.g. pytorch, torchvision version. I am assuming you are using Python 2.7? Since it will not be supported soon and since there are many conflicts between versions relating pytorch, CUDA etc. I wonder if it is possible to make it work for Python3 easily? 

Update: For anyone wondering, I made it work with Python2.7 and pytorch 0.4.0
